# Generated by Django 5.2.8 on 2026-09-07 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable public handle for anonymous order-status lookups — never expose the sequential integer PK to storefront customers.', unique=True),
        ),
    ]
