# Generated by Django 5.2.8 on 2026-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_public_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('needs_attention', 'Needs Attention')], default='pending', max_length=20),
        ),
    ]
